config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"

  resources :tasks do
    member do
      patch :complete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[complete destroy update edit]

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def edit; end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: "Task was successfully created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: "Post was successfully deleted."
  end

  def complete
    @task.update(completed: params[:completed])

    render json: { message: "Success" }
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stimulus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.slim
- if resource.errors.any?
  #error_explanation
    h2
      = pluralize(resource.errors.count, "error")
      prohibited this task from being saved:
    ul
      - resource.errors.full_messages.each do |message|
        li = message

app/views/shared/_notice.slim
- if notice.present?
  p.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block#notice
    = notice

app/views/tasks/_form.slim
= form_for task, html: { class: 'mb-7', data: { turbo: false } }  do |f|
  = render 'shared/error_messages', resource: f.object

  .mb-5
    = f.text_field :description, placeholder: "Add new task", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none"
    = f.submit 'Save', class: "btn py-2 ml-2 bg-blue-600 text-white"

app/views/tasks/_task.slim
turbo-frame[id="#{dom_id task}" class="block mb-2"]
  = form_for task, html: { class: "text-lg inline-block my-3 w-72" } do |f|
    = f.check_box :completed,
                  data: { action: "tasks#toggle", url: complete_task_path(task) },
                  class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500"
    = task.description

  = link_to "Edit", edit_task_path(task), class: "btn bg-gray-100"

  .inline-block.ml-2
    = button_to "Delete", task_path(task),
                          data: { "turbo-frame": "_top" },
                          method: :delete,
                          class: "btn bg-red-100"

app/views/tasks/edit.slim
div
  h1.font-bold.text-2xl.mb-3 Editing Task

  turbo-frame[id="#{dom_id(@task)}"]
    = render "form", task: @task
    = link_to "Never Mind", tasks_path, class: "btn mb-3 bg-gray-100"

app/views/tasks/index.slim
h1.font-bold.text-2xl Task Manager

= render "shared/notice"

.mt-4
  = render "form", task: @task

#tasks[data = { controller: "tasks" }]
  h1.font-bold.text-lg.mb-7 Tasks
  .px-5
    = render @tasks